server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spa_bosque
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update   # en prod: flyway + validate
    properties:
      hibernate:
        format-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.orm.jdbc.bind]": trace

# Si además quieres declarar orígenes CORS aquí (opcional, ya tienes CorsConfig en Java):
# app:
#   cors:
#     allowed-origins:
#       - http://localhost:5173
